/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as InstituicoesEscolhaRouteImport } from './routes/instituicoes-escolha'
import { Route as InstituicoesRouteImport } from './routes/instituicoes'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as ConfirmacaoRouteImport } from './routes/confirmacao'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstituicaoIdRouteImport } from './routes/instituicao.$id'
import { Route as ColecaoCategoriaRouteImport } from './routes/colecao.$categoria'
import { Route as ColecaoRouteImport } from './routes/colecao.'

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituicoesEscolhaRoute = InstituicoesEscolhaRouteImport.update({
  id: '/instituicoes-escolha',
  path: '/instituicoes-escolha',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituicoesRoute = InstituicoesRouteImport.update({
  id: '/instituicoes',
  path: '/instituicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoRoute = ConfirmacaoRouteImport.update({
  id: '/confirmacao',
  path: '/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituicaoIdRoute = InstituicaoIdRouteImport.update({
  id: '/instituicao/$id',
  path: '/instituicao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoCategoriaRoute = ColecaoCategoriaRouteImport.update({
  id: '/colecao/$categoria',
  path: '/colecao/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoRoute = ColecaoRouteImport.update({
  id: '/colecao/',
  path: '/colecao/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/historia': typeof HistoriaRoute
  '/inicio': typeof InicioRoute
  '/instituicoes': typeof InstituicoesRoute
  '/instituicoes-escolha': typeof InstituicoesEscolhaRoute
  '/pagamento': typeof PagamentoRoute
  '/painel': typeof PainelRoute
  '/colecao/': typeof ColecaoRoute
  '/colecao/$categoria': typeof ColecaoCategoriaRoute
  '/instituicao/$id': typeof InstituicaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/historia': typeof HistoriaRoute
  '/inicio': typeof InicioRoute
  '/instituicoes': typeof InstituicoesRoute
  '/instituicoes-escolha': typeof InstituicoesEscolhaRoute
  '/pagamento': typeof PagamentoRoute
  '/painel': typeof PainelRoute
  '/colecao': typeof ColecaoRoute
  '/colecao/$categoria': typeof ColecaoCategoriaRoute
  '/instituicao/$id': typeof InstituicaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/historia': typeof HistoriaRoute
  '/inicio': typeof InicioRoute
  '/instituicoes': typeof InstituicoesRoute
  '/instituicoes-escolha': typeof InstituicoesEscolhaRoute
  '/pagamento': typeof PagamentoRoute
  '/painel': typeof PainelRoute
  '/colecao/': typeof ColecaoRoute
  '/colecao/$categoria': typeof ColecaoCategoriaRoute
  '/instituicao/$id': typeof InstituicaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/confirmacao'
    | '/historia'
    | '/inicio'
    | '/instituicoes'
    | '/instituicoes-escolha'
    | '/pagamento'
    | '/painel'
    | '/colecao/'
    | '/colecao/$categoria'
    | '/instituicao/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/confirmacao'
    | '/historia'
    | '/inicio'
    | '/instituicoes'
    | '/instituicoes-escolha'
    | '/pagamento'
    | '/painel'
    | '/colecao'
    | '/colecao/$categoria'
    | '/instituicao/$id'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/confirmacao'
    | '/historia'
    | '/inicio'
    | '/instituicoes'
    | '/instituicoes-escolha'
    | '/pagamento'
    | '/painel'
    | '/colecao/'
    | '/colecao/$categoria'
    | '/instituicao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  ConfirmacaoRoute: typeof ConfirmacaoRoute
  HistoriaRoute: typeof HistoriaRoute
  InicioRoute: typeof InicioRoute
  InstituicoesRoute: typeof InstituicoesRoute
  InstituicoesEscolhaRoute: typeof InstituicoesEscolhaRoute
  PagamentoRoute: typeof PagamentoRoute
  PainelRoute: typeof PainelRoute
  ColecaoRoute: typeof ColecaoRoute
  ColecaoCategoriaRoute: typeof ColecaoCategoriaRoute
  InstituicaoIdRoute: typeof InstituicaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituicoes-escolha': {
      id: '/instituicoes-escolha'
      path: '/instituicoes-escolha'
      fullPath: '/instituicoes-escolha'
      preLoaderRoute: typeof InstituicoesEscolhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituicoes': {
      id: '/instituicoes'
      path: '/instituicoes'
      fullPath: '/instituicoes'
      preLoaderRoute: typeof InstituicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao': {
      id: '/confirmacao'
      path: '/confirmacao'
      fullPath: '/confirmacao'
      preLoaderRoute: typeof ConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituicao/$id': {
      id: '/instituicao/$id'
      path: '/instituicao/$id'
      fullPath: '/instituicao/$id'
      preLoaderRoute: typeof InstituicaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/$categoria': {
      id: '/colecao/$categoria'
      path: '/colecao/$categoria'
      fullPath: '/colecao/$categoria'
      preLoaderRoute: typeof ColecaoCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/': {
      id: '/colecao/'
      path: '/colecao'
      fullPath: '/colecao/'
      preLoaderRoute: typeof ColecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  ConfirmacaoRoute: ConfirmacaoRoute,
  HistoriaRoute: HistoriaRoute,
  InicioRoute: InicioRoute,
  InstituicoesRoute: InstituicoesRoute,
  InstituicoesEscolhaRoute: InstituicoesEscolhaRoute,
  PagamentoRoute: PagamentoRoute,
  PainelRoute: PainelRoute,
  ColecaoRoute: ColecaoRoute,
  ColecaoCategoriaRoute: ColecaoCategoriaRoute,
  InstituicaoIdRoute: InstituicaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
